app:
    resource: "@AppBundle/Controller/"
    type:     annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    #path: /login_facebook
    path: /login/check-facebook

google_login:
    path: /login/check-google

#the:
#    resource: "@AppBundle/Resources/config/routing.yml"
#    prefix:   /