# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        mohey_db_provider:
            entity:
               class: AppBundle:User
        hwi_provider:       
            id: mohey.aouth_user_provider       
        #my_custom_hwi_provider:
        #    id: hwi_oauth.user.provider.entity

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            pattern:    ^/
            oauth:
                resource_owners:
                    #facebook:      /login_facebook
                    #google:        /login_google
                    facebook:       "/login/check-facebook"
                    google:         "/login/check-google"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: mohey.aouth_user_provider
                    #service: hwi_oauth.user.provider.entity

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/userpanel, roles: ROLE_USER }
    #    - { path: ^/user, roles: ROLE_USER }
        #- { path: ^/admin, roles: ROLE_SUPER_ADMIN }