# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.user_locale_listener:
        class: AppBundle\EventListener\UserLocaleListener
        arguments: ["@session"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
    mohey.aouth_user_provider:
        class: AppBundle\Provider\OAuthUserProvider
        arguments: ["@session", "@doctrine", "@admin.checker", "@request_stack", "@logger_help"]
    #hwi_oauth.user.provider.entity:
    #    class: AppBundle\Provider\Provider
    #    arguments: [@session, @doctrine, @admin.checker, @request_stack]
    admin.checker:
        class: AppBundle\Provider\AdminChecker
        arguments: ["@doctrine", %admins%]
    logger_help:
        class: AppBundle\Common\LoggerHelp
        arguments: ["@logger"]    